### ISSUE TITLE
你好，请问有 Android  的 Demo 提供吗？

### ISSUE THREAD

**Issue by zhangyongcun** [BigVan/FFASR-OpenAPI-Demos#1]
你好，请问有 Android  的 Demo 提供吗？ Android 推荐使用那个类库连接服务器？感谢。

**Comment by BigVan** [comment]
不好意思，暂时没有哦。 目前ffasr处于测试阶段，相关工具还在研发中....

**Comment by zhangyongcun** [comment]
我们申请了公测，发现只有一个 java 的代码可以参考，方面说下如果 Android  平台对接，采用的开源库和大概思路吗？

**Comment by BigVan** [comment]
根据Readme文档的接入规范，与服务器建立websocket请求即可，理论上任意支持websocket协议的库都能接入。
为了避免数据拥塞，报文不宜过长，发报文时请尽量发送1600 or 6400字节长度的报文。
